export const ADMIN_INTERSHIPS_REQUEST = "ADMIN_INTERSHIPS_REQUEST";
export const ADMIN_INTERSHIPS_SUCCESS = "ADMIN_INTERSHIPS_SUCCESS";
export const ADMIN_INTERSHIPS_FAIL = "ADMIN_INTERSHIPS_FAIL";
export const ADMIN_INTERSHIPS_RESET = "ADMIN_INTERSHIPS_RESET";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
