export const APPLIED_INTERSHIP_REQUEST = "APPLIED_INTERSHIP_REQUEST";
export const APPLIED_INTERSHIP_SUCCESS = "APPLIED_INTERSHIP_SUCCESS";
export const APPLIED_INTERSHIP_FAIL = "APPLIED_INTERSHIP_FAIL";

export const LIST_APPLIED_INTERSHIP_REQUEST = "LIST_APPLIED_INTERSHIP_REQUEST";
export const LIST_APPLIED_INTERSHIP_SUCCESS = "LIST_APPLIED_INTERSHIP_SUCCESS";
export const LIST_APPLIED_INTERSHIP_FAIL = "LIST_APPLIED_INTERSHIP_FAIL";
