export const CREATE_INTERNSHIP_REQUEST = "CREATE_INTERNSHIP_REQUEST";
export const CREATE_INTERNSHIP_SUCCESS = "CREATE_INTERNSHIP_SUCCESS";
export const CREATE_INTERNSHIP_FAIL = "CREATE_INTERNSHIP_FAIL";
export const CREATE_INTERNSHIP_RESET = "CREATE_INTERNSHIP_RESET";

export const INTERNSHIPS_LIST_REQUEST = "INTERNSHIPS_LIST_REQUEST";
export const INTERNSHIPS_LIST_SUCCESS = "INTERNSHIPS_LIST_SUCCESS";
export const INTERNSHIPS_LIST_FAIL = "INTERNSHIPS_LIST_FAIL";
