export const CREATE_INTERNSHIP_REQUEST = "CREATE_INTERNSHIP_REQUEST";
export const CREATE_INTERNSHIP_SUCCESS = "CREATE_INTERNSHIP_SUCCESS";
export const CREATE_INTERNSHIP_FAIL = "CREATE_INTERNSHIP_FAIL";
export const CREATE_INTERNSHIP_FAIL = "CREATE_INTERNSHIP_FAIL";
