export const INTERN_LOGIN_REQUEST = "INTERN_LOGIN_REQUEST";
export const INTERN_LOGIN_SUCCESS = "INTERN_LOGIN_SUCCESS";
export const INTERN_LOGIN_FAIL = "INTERN_LOGIN_FAL";
export const INTERN_LOGOUT = "INTERN_LOGOUT";
